### ISSUE TITLE
Fix link to docs in pkgs.racket-lang.org

### ISSUE THREAD

**Issue by pmatos** [bbusching/libgit2#3] opened 2018-03-24 12:28 UTC
Link to docs is broken:
https://pkgs.racket-lang.org/package/libgit2

**Comment by jbclements** [comment] 2018-03-24 20:41
I'm seeing some very strange stuff here; installing locally and then using 
```
raco docs libgit2
```

seems to jump to the file called index.scrbl... I almost wonder if this is a file-system hygiene issue, where the file "index.scrbl" is creating an "index.html" that's stomping the correct index.html.

**Comment by jbclements** [comment] 2018-03-25 00:29
Well, I think it could be one of a whole number of items causing this problem. I'm going to fix them one at a time, to see what the problem is.

First off, it turned out that the scribble file was named "manual.scrbl", which means that the documentation goes into a directory named "manual", rather than "libgit2", which was very confusing. I've changed this, and I'll wait for the package server to rebuild to see if it fixes the problem. 

(I'm guessing it won't.)

Other things to fix:
1) change the name of the "index.scrbl" file to something else. (looks like this won't work, I think the file names are generated from the documented module names, not the source file. Not 100% sure about this.
2) make sure that the file names that are included actually match the named files... currently I believe they differ in upper/lower case; Mac OS X file system is still set to case insensitive by default
3) change the name of the module from index to something else. I'm pretty sure this will work, but it's a pretty intrusive change.

**Comment by LiberalArtist** [comment] 2019-02-08 01:27
The primary issue here should be fixed by writing `@title[#:tag "libgit2_include_index"]{Index}` instead of `@title{Index}`, which generated the tag `"index"`.

There are other issues in the docs, like a lack of `for-label` requires, but the links should be un-broken now. (They are on my machine.)

**Comment by samth** [comment] 2019-04-30 14:48
This got "fixed" in racket/scribble#195 but that breaks the libgit2 doc build.

**Closed as completed** 2019-04-30 23:21 UTC
